### ISSUE TITLE
dataset_util (from object_detection)

### ISSUE THREAD

**Issue by xiaozhuge080** [lukealexmiller/datasets_to_tfrecord#1]
I found the module (dataset_util) in your code, but I don't know where it is. I can't find it in your code, can you help me?
Thanks!

**Comment by lukealexmiller** [comment]
See: https://github.com/tensorflow/models/blob/master/research/object_detection/utils/dataset_util.py

It’s part of TF Object Detection API, but the functions can also be copied from there to remove the dependency.
